Start and enable virtlogd service on compute nodes
This is needed since SLE12SP2 and fixes:

libvirtError: Failed to connect socket to '/var/run/libvirt/virtlogd-sock': \
              No such file or directory