Use openstackclient to create security group rules
python-novaclient no longer supports this operation and fails with:

error: argument <subcommand>: invalid choice: u'secgroup-add-rule'